export const enums = {
  INITIAL_STATE: 'INITIAL_STATE',
  TEST_STATE: 'TEST_STATE',
  ITEMS_FETCH: "ITEMS_FETCH",
  SINGLE_ITEM_FETCH: "SINGLE_ITEM_FETCH",
  SINGLE_ITEM_Remove: "SINGLE_ITEM_Remove"
};